name: Mise à jour Parfums

on:
  workflow_dispatch:

  schedule:
    - cron: "23 6 * * 1"
      timezone: "Europe/Paris"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v6

      - name: Installer Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Installer les dépendances
        run: npm install

      - name: Installer Chromium
        run: npx playwright install --with-deps chromium

      - name: Mettre à jour Zara et Lattafa
        run: npm run scrape

      - name: Valider les données
        run: npm run validate

      - name: Sauvegarder les données
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/products.json data/history

          if git diff --cached --quiet; then
            echo "Aucune modification."
          else
            git commit -m "Mise à jour parfums"
            git push
          fi
